[cite_start]// PDF 파일의 성경 읽기 계획표 전체 데이터 [cite: 9, 210, 287, 292]
export const scheduleData = [
  { "id": 1, "bibleBook": "창세기", "chapters": "1-3", "category": "모세의 기록", "specialNote": null },
  { "id": 2, "bibleBook": "창세기", "chapters": "4-7", "category": "모세의 기록", "specialNote": null },
  { "id": 3, "bibleBook": "창세기", "chapters": "8-11", "category": "모세의 기록", "specialNote": null },
  { "id": 4, "bibleBook": "창세기", "chapters": "12-15", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 5, "bibleBook": "창세기", "chapters": "16-18", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 6, "bibleBook": "창세기", "chapters": "19-22", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 7, "bibleBook": "창세기", "chapters": "23-24", "category": "모세의 기록", "specialNote": null },
  { "id": 8, "bibleBook": "창세기", "chapters": "25-27", "category": "모세의 기록", "specialNote": null },
  { "id": 9, "bibleBook": "창세기", "chapters": "28-30", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 10, "bibleBook": "창세기", "chapters": "31-32", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 11, "bibleBook": "창세기", "chapters": "33-34", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 12, "bibleBook": "창세기", "chapters": "35-37", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 13, "bibleBook": "창세기", "chapters": "38-40", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 14, "bibleBook": "창세기", "chapters": "41-42", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 15, "bibleBook": "창세기", "chapters": "43-45", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 16, "bibleBook": "창세기", "chapters": "46-48", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 17, "bibleBook": "창세기", "chapters": "49-50", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 18, "bibleBook": "출애굽기", "chapters": "1-4", "category": "모세의 기록", "specialNote": null },
  { "id": 19, "bibleBook": "출애굽기", "chapters": "5-7", "category": "모세의 기록", "specialNote": null },
  { "id": 20, "bibleBook": "출애굽기", "chapters": "8-10", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 21, "bibleBook": "출애굽기", "chapters": "11-13", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 22, "bibleBook": "출애굽기", "chapters": "14-15", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 23, "bibleBook": "출애굽기", "chapters": "16-18", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 24, "bibleBook": "출애굽기", "chapters": "19-21", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 25, "bibleBook": "출애굽기", "chapters": "22-25", "category": "모세의 기록", "specialNote": null },
  { "id": 26, "bibleBook": "출애굽기", "chapters": "26-28", "category": "모세의 기록", "specialNote": null },
  { "id": 27, "bibleBook": "출애굽기", "chapters": "29-30", "category": "모세의 기록", "specialNote": null },
  { "id": 28, "bibleBook": "출애굽기", "chapters": "31-33", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 29, "bibleBook": "출애굽기", "chapters": "34-35", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 30, "bibleBook": "출애굽기", "chapters": "36-38", "category": "모세의 기록", "specialNote": null },
  { "id": 31, "bibleBook": "출애굽기", "chapters": "39-40", "category": "모세의 기록", "specialNote": null },
  { "id": 32, "bibleBook": "레위기", "chapters": "1-4", "category": "모세의 기록", "specialNote": null },
  { "id": 33, "bibleBook": "레위기", "chapters": "5-7", "category": "모세의 기록", "specialNote": null },
  { "id": 34, "bibleBook": "레위기", "chapters": "8-10", "category": "모세의 기록", "specialNote": null },
  { "id": 35, "bibleBook": "레위기", "chapters": "11-13", "category": "모세의 기록", "specialNote": null },
  { "id": 36, "bibleBook": "레위기", "chapters": "14-15", "category": "모세의 기록", "specialNote": null },
  { "id": 37, "bibleBook": "레위기", "chapters": "16-18", "category": "모세의 기록", "specialNote": null },
  { "id": 38, "bibleBook": "레위기", "chapters": "19-21", "category": "모세의 기록", "specialNote": null },
  { "id": 39, "bibleBook": "레위기", "chapters": "22-23", "category": "모세의 기록", "specialNote": null },
  { "id": 40, "bibleBook": "레위기", "chapters": "24-25", "category": "모세의 기록", "specialNote": null },
  { "id": 41, "bibleBook": "레위기", "chapters": "26-27", "category": "모세의 기록", "specialNote": null },
  { "id": 42, "bibleBook": "민수기", "chapters": "1-3", "category": "모세의 기록", "specialNote": null },
  { "id": 43, "bibleBook": "민수기", "chapters": "4-6", "category": "모세의 기록", "specialNote": null },
  { "id": 44, "bibleBook": "민수기", "chapters": "7-9", "category": "모세의 기록", "specialNote": null },
  { "id": 45, "bibleBook": "민수기", "chapters": "10-12", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 46, "bibleBook": "민수기", "chapters": "13-15", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 47, "bibleBook": "민수기", "chapters": "16-18", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 48, "bibleBook": "민수기", "chapters": "19-21", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 49, "bibleBook": "민수기", "chapters": "22-24", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 50, "bibleBook": "민수기", "chapters": "25-27", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 51, "bibleBook": "민수기", "chapters": "28-30", "category": "모세의 기록", "specialNote": null },
  { "id": 52, "bibleBook": "민수기", "chapters": "31-32", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 53, "bibleBook": "민수기", "chapters": "33-36", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 54, "bibleBook": "신명기", "chapters": "1-2", "category": "모세의 기록", "specialNote": null },
  { "id": 55, "bibleBook": "신명기", "chapters": "3-4", "category": "모세의 기록", "specialNote": null },
  { "id": 56, "bibleBook": "신명기", "chapters": "5-7", "category": "모세의 기록", "specialNote": null },
  { "id": 57, "bibleBook": "신명기", "chapters": "8-10", "category": "모세의 기록", "specialNote": null },
  { "id": 58, "bibleBook": "신명기", "chapters": "11-13", "category": "모세의 기록", "specialNote": null },
  { "id": 59, "bibleBook": "신명기", "chapters": "14-16", "category": "모세의 기록", "specialNote": null },
  { "id": 60, "bibleBook": "신명기", "chapters": "17-19", "category": "모세의 기록", "specialNote": null },
  { "id": 61, "bibleBook": "신명기", "chapters": "20-22", "category": "모세의 기록", "specialNote": null },
  { "id": 62, "bibleBook": "신명기", "chapters": "23-26", "category": "모세의 기록", "specialNote": null },
  { "id": 63, "bibleBook": "신명기", "chapters": "27-28", "category": "모세의 기록", "specialNote": null },
  { "id": 64, "bibleBook": "신명기", "chapters": "29-30", "category": "모세의 기록", "specialNote": null },
  { "id": 65, "bibleBook": "신명기", "chapters": "31-33", "category": "모세의 기록", "specialNote": "이스라엘 역사" },
  { "id": 66, "bibleBook": "신명기", "chapters": "34", "category": "모세의 기록", "specialNote": null },
  { "id": 67, "bibleBook": "여호수아", "chapters": "1-4", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": null },
  { "id": 68, "bibleBook": "여호수아", "chapters": "5-7", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": null },
  { "id": 69, "bibleBook": "여호수아", "chapters": "8-9", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": null },
  { "id": 70, "bibleBook": "여호수아", "chapters": "10-12", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": "이스라엘 역사" },
  { "id": 71, "bibleBook": "여호수아", "chapters": "13-15", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": "이스라엘 역사" },
  { "id": 72, "bibleBook": "여호수아", "chapters": "16-18", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": "이스라엘 역사" },
  { "id": 73, "bibleBook": "여호수아", "chapters": "19-21", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": "이스라엘 역사" },
  { "id": 74, "bibleBook": "여호수아", "chapters": "22-24", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": "이스라엘 역사" },
  { "id": 75, "bibleBook": "사사기", "chapters": "1-2", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": null },
  { "id": 76, "bibleBook": "사사기", "chapters": "3-5", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": "이스라엘 역사" },
  { "id": 77, "bibleBook": "사사기", "chapters": "6-7", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": null },
  { "id": 78, "bibleBook": "사사기", "chapters": "8-9", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": null },
  { "id": 79, "bibleBook": "사사기", "chapters": "10-11", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": "이스라엘 역사" },
  { "id": 80, "bibleBook": "사사기", "chapters": "12-13", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": "이스라엘 역사" },
  { "id": 81, "bibleBook": "사사기", "chapters": "14-16", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": "이스라엘 역사" },
  { "id": 82, "bibleBook": "사사기", "chapters": "17-19", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": "이스라엘 역사" },
  { "id": 83, "bibleBook": "사사기", "chapters": "20-21", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": "이스라엘 역사" },
  { "id": 84, "bibleBook": "룻기", "chapters": "1-4", "category": "이스라엘이 약속의 땅에 들어가다", "specialNote": null },
  { "id": 85, "bibleBook": "사무엘상", "chapters": "1-2", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 86, "bibleBook": "사무엘상", "chapters": "3-6", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 87, "bibleBook": "사무엘상", "chapters": "7-9", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 88, "bibleBook": "사무엘상", "chapters": "10-12", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 89, "bibleBook": "사무엘상", "chapters": "13-14", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 90, "bibleBook": "사무엘상", "chapters": "15-16", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 91, "bibleBook": "사무엘상", "chapters": "17-18", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 92, "bibleBook": "사무엘상", "chapters": "19-21", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 93, "bibleBook": "사무엘상", "chapters": "22-24", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 94, "bibleBook": "사무엘상", "chapters": "25-27", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 95, "bibleBook": "사무엘상", "chapters": "28-31", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 96, "bibleBook": "사무엘하", "chapters": "1-2", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 97, "bibleBook": "사무엘하", "chapters": "3-5", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 98, "bibleBook": "사무엘하", "chapters": "6-8", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 99, "bibleBook": "사무엘하", "chapters": "9-12", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 100, "bibleBook": "사무엘하", "chapters": "13-14", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 101, "bibleBook": "사무엘하", "chapters": "15-16", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 102, "bibleBook": "사무엘하", "chapters": "17-18", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 103, "bibleBook": "사무엘하", "chapters": "19-20", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 104, "bibleBook": "사무엘하", "chapters": "21-22", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 105, "bibleBook": "사무엘하", "chapters": "23-24", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 106, "bibleBook": "열왕기상", "chapters": "1-2", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 107, "bibleBook": "열왕기상", "chapters": "3-5", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 108, "bibleBook": "열왕기상", "chapters": "6-7", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 109, "bibleBook": "열왕기상", "chapters": "8", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 110, "bibleBook": "열왕기상", "chapters": "9-10", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 111, "bibleBook": "열왕기상", "chapters": "11-12", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 112, "bibleBook": "열왕기상", "chapters": "13-14", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 113, "bibleBook": "열왕기상", "chapters": "15-17", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 114, "bibleBook": "열왕기상", "chapters": "18-19", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 115, "bibleBook": "열왕기상", "chapters": "20-21", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 116, "bibleBook": "열왕기상", "chapters": "22", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 117, "bibleBook": "열왕기하", "chapters": "1-3", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 118, "bibleBook": "열왕기하", "chapters": "4-5", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 119, "bibleBook": "열왕기하", "chapters": "6-8", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 120, "bibleBook": "열왕기하", "chapters": "9-10", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 121, "bibleBook": "열왕기하", "chapters": "11-13", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 122, "bibleBook": "열왕기하", "chapters": "14-15", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 123, "bibleBook": "열왕기하", "chapters": "16-17", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 124, "bibleBook": "열왕기하", "chapters": "18-19", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 125, "bibleBook": "열왕기하", "chapters": "20-22", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 126, "bibleBook": "열왕기하", "chapters": "23-25", "category": "이스라엘의 왕정 시대", "specialNote": "이스라엘 역사" },
  { "id": 127, "bibleBook": "역대기상", "chapters": "1-2", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 128, "bibleBook": "역대기상", "chapters": "3-5", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 129, "bibleBook": "역대기상", "chapters": "6-7", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 130, "bibleBook": "역대기상", "chapters": "8-10", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 131, "bibleBook": "역대기상", "chapters": "11-12", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 132, "bibleBook": "역대기상", "chapters": "13-15", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 133, "bibleBook": "역대기상", "chapters": "16-17", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 134, "bibleBook": "역대기상", "chapters": "18-20", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 135, "bibleBook": "역대기상", "chapters": "21-23", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 136, "bibleBook": "역대기상", "chapters": "24-26", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 137, "bibleBook": "역대기상", "chapters": "27-29", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 138, "bibleBook": "역대기하", "chapters": "1-3", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 139, "bibleBook": "역대기하", "chapters": "4-6", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 140, "bibleBook": "역대기하", "chapters": "7-9", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 141, "bibleBook": "역대기하", "chapters": "10-14", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 142, "bibleBook": "역대기하", "chapters": "15-18", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 143, "bibleBook": "역대기하", "chapters": "19-20", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 144, "bibleBook": "역대기하", "chapters": "21-24", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 145, "bibleBook": "역대기하", "chapters": "25-28", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 146, "bibleBook": "역대기하", "chapters": "29-30", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 147, "bibleBook": "역대기하", "chapters": "31-33", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 148, "bibleBook": "역대기하", "chapters": "34-36", "category": "이스라엘의 왕정 시대", "specialNote": null },
  { "id": 149, "bibleBook": "에스라", "chapters": "1-3", "category": "유대인들이 유배 생활에서 돌아오다", "specialNote": null },
  { "id": 150, "bibleBook": "에스라", "chapters": "4-7", "category": "유대인들이 유배 생활에서 돌아오다", "specialNote": null },
  { "id": 151, "bibleBook": "에스라", "chapters": "8-10", "category": "유대인들이 유배 생활에서 돌아오다", "specialNote": "이스라엘 역사" },
  { "id": 152, "bibleBook": "느헤미야", "chapters": "1-3", "category": "유대인들이 유배 생활에서 돌아오다", "specialNote": null },
  { "id": 153, "bibleBook": "느헤미야", "chapters": "4-6", "category": "유대인들이 유배 생활에서 돌아오다", "specialNote": null },
  { "id": 154, "bibleBook": "느헤미야", "chapters": "7-8", "category": "유대인들이 유배 생활에서 돌아오다", "specialNote": null },
  { "id": 155, "bibleBook": "느헤미야", "chapters": "9-10", "category": "유대인들이 유배 생활에서 돌아오다", "specialNote": "이스라엘 역사" },
  { "id": 156, "bibleBook": "느헤미야", "chapters": "11-13", "category": "유대인들이 유배 생활에서 돌아오다", "specialNote": "이스라엘 역사" },
  { "id": 157, "bibleBook": "에스더", "chapters": "1-4", "category": "유대인들이 유배 생활에서 돌아오다", "specialNote": null },
  { "id": 158, "bibleBook": "에스더", "chapters": "5-10", "category": "유대인들이 유배 생활에서 돌아오다", "specialNote": null },
  { "id": 159, "bibleBook": "욥기", "chapters": "1-5", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 160, "bibleBook": "욥기", "chapters": "6-9", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 161, "bibleBook": "욥기", "chapters": "10-14", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 162, "bibleBook": "욥기", "chapters": "15-18", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 163, "bibleBook": "욥기", "chapters": "19-20", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 164, "bibleBook": "욥기", "chapters": "21-24", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 165, "bibleBook": "욥기", "chapters": "25-29", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 166, "bibleBook": "욥기", "chapters": "30-31", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 167, "bibleBook": "욥기", "chapters": "32-34", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 168, "bibleBook": "욥기", "chapters": "35-38", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 169, "bibleBook": "욥기", "chapters": "39-42", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 170, "bibleBook": "시편", "chapters": "1-8", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 171, "bibleBook": "시편", "chapters": "9-16", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 172, "bibleBook": "시편", "chapters": "17-19", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 173, "bibleBook": "시편", "chapters": "20-25", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 174, "bibleBook": "시편", "chapters": "26-31", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 175, "bibleBook": "시편", "chapters": "32-35", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 176, "bibleBook": "시편", "chapters": "36-38", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 177, "bibleBook": "시편", "chapters": "39-42", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 178, "bibleBook": "시편", "chapters": "43-47", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 179, "bibleBook": "시편", "chapters": "48-52", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 180, "bibleBook": "시편", "chapters": "53-58", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 181, "bibleBook": "시편", "chapters": "59-64", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 182, "bibleBook": "시편", "chapters": "65-68", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 183, "bibleBook": "시편", "chapters": "69-72", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 184, "bibleBook": "시편", "chapters": "73-77", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 185, "bibleBook": "시편", "chapters": "78-79", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 186, "bibleBook": "시편", "chapters": "80-86", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 187, "bibleBook": "시편", "chapters": "87-90", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 188, "bibleBook": "시편", "chapters": "91-96", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 189, "bibleBook": "시편", "chapters": "97-103", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 190, "bibleBook": "시편", "chapters": "104-105", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 191, "bibleBook": "시편", "chapters": "106-108", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 192, "bibleBook": "시편", "chapters": "109-115", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 193, "bibleBook": "시편", "chapters": "116-119:63", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 194, "bibleBook": "시편", "chapters": "119:64-176", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 195, "bibleBook": "시편", "chapters": "120-129", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 196, "bibleBook": "시편", "chapters": "130-138", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 197, "bibleBook": "시편", "chapters": "139-144", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 198, "bibleBook": "시편", "chapters": "145-150", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 199, "bibleBook": "잠언", "chapters": "1-4", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 200, "bibleBook": "잠언", "chapters": "5-8", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 201, "bibleBook": "잠언", "chapters": "9-12", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 202, "bibleBook": "잠언", "chapters": "13-16", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 203, "bibleBook": "잠언", "chapters": "17-19", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 204, "bibleBook": "잠언", "chapters": "20-22", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 205, "bibleBook": "잠언", "chapters": "23-27", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 206, "bibleBook": "잠언", "chapters": "28-31", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 207, "bibleBook": "전도서", "chapters": "1-4", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 208, "bibleBook": "전도서", "chapters": "5-8", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 209, "bibleBook": "전도서", "chapters": "9-12", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 210, "bibleBook": "솔로몬의 노래", "chapters": "1-8", "category": "노래와 실용적인 조언이 담긴 책", "specialNote": null },
  { "id": 211, "bibleBook": "이사야", "chapters": "1-4", "category": "예언서", "specialNote": null },
  { "id": 212, "bibleBook": "이사야", "chapters": "5-7", "category": "예언서", "specialNote": null },
  { "id": 213, "bibleBook": "이사야", "chapters": "8-10", "category": "예언서", "specialNote": null },
  { "id": 214, "bibleBook": "이사야", "chapters": "11-14", "category": "예언서", "specialNote": null },
  { "id": 215, "bibleBook": "이사야", "chapters": "15-19", "category": "예언서", "specialNote": null },
  { "id": 216, "bibleBook": "이사야", "chapters": "20-24", "category": "예언서", "specialNote": null },
  { "id": 217, "bibleBook": "이사야", "chapters": "25-28", "category": "예언서", "specialNote": null },
  { "id": 218, "bibleBook": "이사야", "chapters": "29-31", "category": "예언서", "specialNote": null },
  { "id": 219, "bibleBook": "이사야", "chapters": "32-35", "category": "예언서", "specialNote": null },
  { "id": 220, "bibleBook": "이사야", "chapters": "36-37", "category": "예언서", "specialNote": null },
  { "id": 221, "bibleBook": "이사야", "chapters": "38-40", "category": "예언서", "specialNote": null },
  { "id": 222, "bibleBook": "이사야", "chapters": "41-43", "category": "예언서", "specialNote": null },
  { "id": 223, "bibleBook": "이사야", "chapters": "44-47", "category": "예언서", "specialNote": null },
  { "id": 224, "bibleBook": "이사야", "chapters": "48-50", "category": "예언서", "specialNote": null },
  { "id": 225, "bibleBook": "이사야", "chapters": "51-55", "category": "예언서", "specialNote": null },
  { "id": 226, "bibleBook": "이사야", "chapters": "56-58", "category": "예언서", "specialNote": null },
  { "id": 227, "bibleBook": "이사야", "chapters": "59-62", "category": "예언서", "specialNote": null },
  { "id": 228, "bibleBook": "이사야", "chapters": "63-66", "category": "예언서", "specialNote": null },
  { "id": 229, "bibleBook": "예레미야", "chapters": "1-3", "category": "예언서", "specialNote": null },
  { "id": 230, "bibleBook": "예레미야", "chapters": "4-5", "category": "예언서", "specialNote": null },
  { "id": 231, "bibleBook": "예레미야", "chapters": "6-7", "category": "예언서", "specialNote": null },
  { "id": 232, "bibleBook": "예레미야", "chapters": "8-10", "category": "예언서", "specialNote": null },
  { "id": 233, "bibleBook": "예레미야", "chapters": "11-13", "category": "예언서", "specialNote": null },
  { "id": 234, "bibleBook": "예레미야", "chapters": "14-16", "category": "예언서", "specialNote": null },
  { "id": 235, "bibleBook": "예레미야", "chapters": "17-20", "category": "예언서", "specialNote": null },
  { "id": 236, "bibleBook": "예레미야", "chapters": "21-23", "category": "예언서", "specialNote": null },
  { "id": 237, "bibleBook": "예레미야", "chapters": "24-26", "category": "예언서", "specialNote": null },
  { "id": 238, "bibleBook": "예레미야", "chapters": "27-29", "category": "예언서", "specialNote": null },
  { "id": 239, "bibleBook": "예레미야", "chapters": "30-31", "category": "예언서", "specialNote": null },
  { "id": 240, "bibleBook": "예레미야", "chapters": "32-33", "category": "예언서", "specialNote": null },
  { "id": 241, "bibleBook": "예레미야", "chapters": "34-36", "category": "예언서", "specialNote": null },
  { "id": 242, "bibleBook": "예레미야", "chapters": "37-39", "category": "예언서", "specialNote": null },
  { "id": 243, "bibleBook": "예레미야", "chapters": "40-42", "category": "예언서", "specialNote": null },
  { "id": 244, "bibleBook": "예레미야", "chapters": "43-44", "category": "예언서", "specialNote": null },
  { "id": 245, "bibleBook": "예레미야", "chapters": "45-48", "category": "예언서", "specialNote": null },
  { "id": 246, "bibleBook": "예레미야", "chapters": "49-50", "category": "예언서", "specialNote": null },
  { "id": 247, "bibleBook": "예레미야", "chapters": "51-52", "category": "예언서", "specialNote": null },
  { "id": 248, "bibleBook": "예레미야 애가", "chapters": "1-2", "category": "예언서", "specialNote": null },
  { "id": 249, "bibleBook": "예레미야 애가", "chapters": "3-5", "category": "예언서", "specialNote": null },
  { "id": 250, "bibleBook": "에스겔", "chapters": "1-3", "category": "예언서", "specialNote": null },
  { "id": 251, "bibleBook": "에스겔", "chapters": "4-6", "category": "예언서", "specialNote": null },
  { "id": 252, "bibleBook": "에스겔", "chapters": "7-9", "category": "예언서", "specialNote": null },
  { "id": 253, "bibleBook": "에스겔", "chapters": "10-12", "category": "예언서", "specialNote": null },
  { "id": 254, "bibleBook": "에스겔", "chapters": "13-15", "category": "예언서", "specialNote": null },
  { "id": 255, "bibleBook": "에스겔", "chapters": "16", "category": "예언서", "specialNote": null },
  { "id": 256, "bibleBook": "에스겔", "chapters": "17-18", "category": "예언서", "specialNote": null },
  { "id": 257, "bibleBook": "에스겔", "chapters": "19-21", "category": "예언서", "specialNote": null },
  { "id": 258, "bibleBook": "에스겔", "chapters": "22-23", "category": "예언서", "specialNote": null },
  { "id": 259, "bibleBook": "에스겔", "chapters": "24-26", "category": "예언서", "specialNote": null },
  { "id": 260, "bibleBook": "에스겔", "chapters": "27-28", "category": "예언서", "specialNote": null },
  { "id": 261, "bibleBook": "에스겔", "chapters": "29-31", "category": "예언서", "specialNote": null },
  { "id": 262, "bibleBook": "에스겔", "chapters": "32-33", "category": "예언서", "specialNote": null },
  { "id": 263, "bibleBook": "에스겔", "chapters": "34-36", "category": "예언서", "specialNote": null },
  { "id": 264, "bibleBook": "에스겔", "chapters": "37-38", "category": "예언서", "specialNote": null },
  { "id": 265, "bibleBook": "에스겔", "chapters": "39-40", "category": "예언서", "specialNote": null },
  { "id": 266, "bibleBook": "에스겔", "chapters": "41-43", "category": "예언서", "specialNote": null },
  { "id": 267, "bibleBook": "에스겔", "chapters": "44-45", "category": "예언서", "specialNote": null },
  { "id": 268, "bibleBook": "에스겔", "chapters": "46-48", "category": "예언서", "specialNote": null },
  { "id": 269, "bibleBook": "다니엘", "chapters": "1-2", "category": "예언서", "specialNote": null },
  { "id": 270, "bibleBook": "다니엘", "chapters": "3-4", "category": "예언서", "specialNote": null },
  { "id": 271, "bibleBook": "다니엘", "chapters": "5-7", "category": "예언서", "specialNote": null },
  { "id": 272, "bibleBook": "다니엘", "chapters": "8-10", "category": "예언서", "specialNote": null },
  { "id": 273, "bibleBook": "다니엘", "chapters": "11-12", "category": "예언서", "specialNote": null },
  { "id": 274, "bibleBook": "호세아", "chapters": "1-7", "category": "예언서", "specialNote": null },
  { "id": 275, "bibleBook": "호세아", "chapters": "8-14", "category": "예언서", "specialNote": null },
  { "id": 276, "bibleBook": "요엘", "chapters": "1-3", "category": "예언서", "specialNote": null },
  { "id": 277, "bibleBook": "아모스", "chapters": "1-5", "category": "예언서", "specialNote": null },
  { "id": 278, "bibleBook": "아모스", "chapters": "6-9", "category": "예언서", "specialNote": null },
  { "id": 279, "bibleBook": "오바댜/요나", "chapters": "전체", "category": "예언서", "specialNote": null },
  { "id": 280, "bibleBook": "미가", "chapters": "1-7", "category": "예언서", "specialNote": null },
  { "id": 281, "bibleBook": "나훔/하박국", "chapters": "전체", "category": "예언서", "specialNote": null },
  { "id": 282, "bibleBook": "스바냐/학개", "chapters": "전체", "category": "예언서", "specialNote": null },
  { "id": 283, "bibleBook": "스가랴", "chapters": "1-7", "category": "예언서", "specialNote": null },
  { "id": 284, "bibleBook": "스가랴", "chapters": "8-11", "category": "예언서", "specialNote": null },
  { "id": 285, "bibleBook": "스가랴", "chapters": "12-14", "category": "예언서", "specialNote": null },
  { "id": 286, "bibleBook": "말라기", "chapters": "1-4", "category": "예언서", "specialNote": null },
  { "id": 287, "bibleBook": "마태복음", "chapters": "1-4", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 288, "bibleBook": "마태복음", "chapters": "5-7", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 289, "bibleBook": "마태복음", "chapters": "8-10", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 290, "bibleBook": "마태복음", "chapters": "11-13", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 291, "bibleBook": "마태복음", "chapters": "14-17", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 292, "bibleBook": "마태복음", "chapters": "18-20", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 293, "bibleBook": "마태복음", "chapters": "21-23", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 294, "bibleBook": "마태복음", "chapters": "24-25", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 295, "bibleBook": "마태복음", "chapters": "26", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 296, "bibleBook": "마태복음", "chapters": "27-28", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 297, "bibleBook": "마가복음", "chapters": "1-3", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 298, "bibleBook": "마가복음", "chapters": "4-5", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 299, "bibleBook": "마가복음", "chapters": "6-7", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 300, "bibleBook": "마가복음", "chapters": "8-9", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 301, "bibleBook": "마가복음", "chapters": "10-12", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 302, "bibleBook": "마가복음", "chapters": "13-16", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 303, "bibleBook": "누가복음", "chapters": "1-2", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 304, "bibleBook": "누가복음", "chapters": "3-5", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 305, "bibleBook": "누가복음", "chapters": "6-7", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 306, "bibleBook": "누가복음", "chapters": "8-9", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 307, "bibleBook": "누가복음", "chapters": "10-11", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 308, "bibleBook": "누가복음", "chapters": "12-13", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 309, "bibleBook": "누가복음", "chapters": "14-17", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 310, "bibleBook": "누가복음", "chapters": "18-19", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 311, "bibleBook": "누가복음", "chapters": "20-22", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 312, "bibleBook": "누가복음", "chapters": "23-24", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 313, "bibleBook": "요한복음", "chapters": "1-3", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 314, "bibleBook": "요한복음", "chapters": "4-5", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 315, "bibleBook": "요한복음", "chapters": "6-7", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 316, "bibleBook": "요한복음", "chapters": "8-9", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 317, "bibleBook": "요한복음", "chapters": "10-12", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 318, "bibleBook": "요한복음", "chapters": "13-15", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 319, "bibleBook": "요한복음", "chapters": "16-18", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 320, "bibleBook": "요한복음", "chapters": "19-21", "category": "예수의 생애와 봉사에 관한 기록", "specialNote": null },
  { "id": 321, "bibleBook": "사도행전", "chapters": "1-3", "category": "그리스도인 회중의 성장", "specialNote": null },
  { "id": 322, "bibleBook": "사도행전", "chapters": "4-6", "category": "그리스도인 회중의 성장", "specialNote": null },
  { "id": 323, "bibleBook": "사도행전", "chapters": "7-8", "category": "그리스도인 회중의 성장", "specialNote": null },
  { "id": 324, "bibleBook": "사도행전", "chapters": "9-11", "category": "그리스도인 회중의 성장", "specialNote": null },
  { "id": 325, "bibleBook": "사도행전", "chapters": "12-14", "category": "그리스도인 회중의 성장", "specialNote": null },
  { "id": 326, "bibleBook": "사도행전", "chapters": "15-16", "category": "그리스도인 회중의 성장", "specialNote": "그리스도인 회중 발전" },
  { "id": 327, "bibleBook": "사도행전", "chapters": "17-19", "category": "그리스도인 회중의 성장", "specialNote": "그리스도인 회중 발전" },
  { "id": 328, "bibleBook": "사도행전", "chapters": "20-21", "category": "그리스도인 회중의 성장", "specialNote": "그리스도인 회중 발전" },
  { "id": 329, "bibleBook": "사도행전", "chapters": "22-23", "category": "그리스도인 회중의 성장", "specialNote": "그리스도인 회중 발전" },
  { "id": 330, "bibleBook": "사도행전", "chapters": "24-26", "category": "그리스도인 회중의 성장", "specialNote": "그리스도인 회중 발전" },
  { "id": 331, "bibleBook": "사도행전", "chapters": "27-28", "category": "그리스도인 회중의 성장", "specialNote": "그리스도인 회중 발전" },
  { "id": 332, "bibleBook": "로마서", "chapters": "1-3", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 333, "bibleBook": "로마서", "chapters": "4-7", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 334, "bibleBook": "로마서", "chapters": "8-11", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 335, "bibleBook": "로마서", "chapters": "12-16", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 336, "bibleBook": "고린도 전서", "chapters": "1-6", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 337, "bibleBook": "고린도 전서", "chapters": "7-10", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 338, "bibleBook": "고린도 전서", "chapters": "11-14", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 339, "bibleBook": "고린도 전서", "chapters": "15-16", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 340, "bibleBook": "고린도후서", "chapters": "1-6", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 341, "bibleBook": "고린도후서", "chapters": "7-10", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 342, "bibleBook": "고린도후서", "chapters": "11-13", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 343, "bibleBook": "갈라디아서", "chapters": "1-6", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 344, "bibleBook": "에베소서", "chapters": "1-6", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 345, "bibleBook": "빌립보서", "chapters": "1-4", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 346, "bibleBook": "골로새서", "chapters": "1-4", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 347, "bibleBook": "데살로니가 전서", "chapters": "1-5", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 348, "bibleBook": "데살로니가 후서", "chapters": "1-3", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 349, "bibleBook": "디모데 전서", "chapters": "1-6", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 350, "bibleBook": "디모데 후서", "chapters": "1-4", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 351, "bibleBook": "디도서/빌레몬서", "chapters": "전체", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 352, "bibleBook": "히브리서", "chapters": "1-6", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 353, "bibleBook": "히브리서", "chapters": "7-10", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 354, "bibleBook": "히브리서", "chapters": "11-13", "category": "바울이 쓴 편지", "specialNote": null },
  { "id": 355, "bibleBook": "야고보서", "chapters": "1-5", "category": "다른 사도와 제자들의 글", "specialNote": null },
  { "id": 356, "bibleBook": "베드로 전서", "chapters": "1-5", "category": "다른 사도와 제자들의 글", "specialNote": null },
  { "id": 357, "bibleBook": "베드로 후서", "chapters": "1-3", "category": "다른 사도와 제자들의 글", "specialNote": null },
  { "id": 358, "bibleBook": "요한 1서", "chapters": "1-5", "category": "다른 사도와 제자들의 글", "specialNote": null },
  { "id": 359, "bibleBook": "요한 2서/요한 3서/유다서", "chapters": "전체", "category": "다른 사도와 제자들의 글", "specialNote": null },
  { "id": 360, "bibleBook": "요한 계시록", "chapters": "1-4", "category": "다른 사도와 제자들의 글", "specialNote": null },
  { "id": 361, "bibleBook": "요한 계시록", "chapters": "5-9", "category": "다른 사도와 제자들의 글", "specialNote": null },
  { "id": 362, "bibleBook": "요한 계시록", "chapters": "10-14", "category": "다른 사도와 제자들의 글", "specialNote": null },
  { "id": 363, "bibleBook": "요한 계시록", "chapters": "15-18", "category": "다른 사도와 제자들의 글", "specialNote": null },
  { "id": 364, "bibleBook": "요한 계시록", "chapters": "19-22", "category": "다른 사도와 제자들의 글", "specialNote": null }
];